version: "3.3"
services:
  db:
    container_name: cheffy_dev_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cheffy_dev_db
    ports:
      - "5432:5432"
    volumes:
      - cheffy_data/:/var/lib/postgresql/data/
    user: root
volumes:
  cheffy_data:
